name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{secrets.AAA_TEST_SECRET}}
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{secrets.AAA_TEST_SECRET}} | sed 's/./& /g'
